<template>
    <div >
        <div >
           <ul class="nav nav-pills">
                <li class="nav-item">
                    <router-link to="/">Home</router-link>  
                </li>
                <li class="nav-item">
                    <router-link to="/Adventures">Active</router-link>  
                </li>
            </ul>
        </div>
    </div>
</template>

<script>
</script>

<style scoped>

</style>
